name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Setup bun store & build artifact cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-bun-
      - name: Install bun dependencies
        run: bun i --no-save
      - name: Install Chrome and add to PATH
        run: |
          TMP_DEB=$(mktemp -d /tmp/deb-XXXXXX)
          TMP_BIN=$(mktemp -d /tmp/bin-XXXXXX)
          cd "$TMP_DEB"
          curl -O https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          ar x google-chrome-stable_current_amd64.deb
          tar -xf data.tar.xz -C "$TMP_BIN" --strip-components=4 ./opt/google
          echo "$TMP_BIN" >> "$GITHUB_PATH"
      - name: Build project artifacts
        run: bun --bun run build
      - name: Deploy project artifacts to Cloudflare Pages
        run: bunx wrangler pages deploy ./out --project-name=omemoji-com --branch main
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
